name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # This will run the action at 12-hour intervals
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v3
        with:
          # GitHub username to read the contribution graph from (**required**)
          # using action context variable `github.repository_owner` or specified user
          github_user_name: Sunera25

          # List of files to generate
          # Each output can be customized with options as a query string
          #
          # Supported options:
          # - palette: A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots: Comma-separated list of dot colors.
          #               The first one is for 0 contributions, then it goes from low to high.
          #               Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Deploy the snake SVG/GIF to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Branch to store the generated assets
          build_dir: dist        # Directory containing the generated SVG/GIF files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
